name: CI
on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        system:
          - { name: azura, platform: ubuntu-24.04 }
          - { name: namira, platform: ubuntu-24.04 }
          - { name: sheogorath, platform: ubuntu-24.04 }
          - { name: jyggalag, platform: ubuntu-24.04-arm }
          # - { name: Xaviers-MacBook-Pro, platform: macos-14 }

    runs-on: ${{ matrix.system.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Make space
        if: startsWith(matrix.system.platform, 'ubuntu')
        uses: wimpysworld/nothing-but-nix@v7

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3.14.0

      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:deploy-rs

      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ vars.ATTIC_ENDPOINT }}
          cache: ${{ vars.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Run ci checks
        run: |
          nix flake check

      - name: Build ${{ matrix.system.name }}
        if: startsWith(matrix.system.platform, 'ubuntu')
        run: |
          nix run nixpkgs#nixos-rebuild -- build --flake .#${{ matrix.system.name }}

      # Fails to resolv host for now for some reason
      # - name: Build (darwin) ${{ matrix.system.name }}
      #   if: startsWith(matrix.system.platform, 'macos')
      #   run: |
      #     nix run .#darwin-rebuild -- build --flake .#${{ matrix.system.name }}
